title: Favorite Foods and Places to Visit
author: Stefan Tan
email: stefantan39@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog containing interesting foods to eat and places to visit. I would definitely recommend you to try these out!

theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  StefanTan18 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
